# Generated by Django 5.1.1 on 2024-11-13 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_mascota_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo', models.CharField(max_length=255)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.cliente')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.mascota')),
            ],
        ),
    ]
